title: "Barnes Demolition"
description: "Wilmington's trusted contractor for residential, commercial, and industrial demolition. Licensed & insured. Call (910) 807-5640."
url: ""
baseurl: "/Barnes-Demolition"
permalink: none
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
